name = "rogue-lab-v1"
main = "src/worker.ts"
compatibility_date = "2026-07-01"
account_id = "8b7ebe7cc8bb9b5579f7b2fe2d6cb431"
workers_dev = false
routes = [
  { pattern = "lab.adrianlumley.co/*", zone_name = "adrianlumley.co" }
]

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "rogue_lab"
database_id = "ae1ac7a9-21b1-4b94-ba4a-3e3911bbd3e5"
